# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cephmgr < Formula
  desc ""
  homepage "https://github.com/blastart-repo/cephmgr"
  version "0.1.2"

  on_macos do
    url "https://github.com/blastart-repo/cephmgr/releases/download/v0.1.2/cephmgr_0.1.2_darwin_all.tar.gz"
    sha256 "0574ee98a3ae27a73e73c0b7dad895712d187a37fcb4b95f190eaa1558c646df"

    def install
      bin.install "cephmgr"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blastart-repo/cephmgr/releases/download/v0.1.2/cephmgr_0.1.2_linux_arm64.tar.gz"
      sha256 "ddc7247f80e4745d4fc90adaba7cf3313fccbff930762f9ff513ae28d3a123ea"

      def install
        bin.install "cephmgr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/blastart-repo/cephmgr/releases/download/v0.1.2/cephmgr_0.1.2_linux_amd64.tar.gz"
      sha256 "b6751f32960f0c62ca9815dd286cc2aa3dcbb5cbce774f31504c64eb29111ef6"

      def install
        bin.install "cephmgr"
      end
    end
  end
end
